/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import { Provider } from "@ethersproject/providers"
import { Contract, Signer } from "ethers"

import type { Vault } from "./Vault"

export class Vault__factory {
    static connect(
        address: string,
        signerOrProvider: Signer | Provider
    ): Vault {
        return new Contract(address, _abi, signerOrProvider) as Vault
    }
}

const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "account",
                type: "address"
            },
            {
                internalType: "uint256[]",
                name: "tokenIds",
                type: "uint256[]"
            }
        ],
        name: "getAccountClaims",
        outputs: [
            {
                internalType: "uint256[]",
                name: "",
                type: "uint256[]"
            }
        ],
        stateMutability: "view",
        type: "function"
    }
]
